#!/bin/bash

# Define the configuration flags as a single variable
PPO_FLAGS="--ref_num_nodes 1 \
    --ref_num_gpus_per_node 4 \
    --colocate_actor_ref \
    --critic_num_nodes 1 \
    --critic_num_gpus_per_node 2 \
    --actor_num_nodes 1 \
    --actor_num_gpus_per_node 4 \
    --packing_samples \
    --vllm_num_engines 1 \
    --vllm_tensor_parallel_size 2 \
    --pretrain ${pretrain_model} \
    --remote_rm_url ${working_dir}/src/cultural_lexis_finetune_llms/pipelines/ppo_further_training/reward_func.py \
    --save_path ${pretrain_model_dir}/${output_tag} \
    --micro_train_batch_size 8 \
    --train_batch_size 32 \
    --micro_rollout_batch_size 16 \
    --rollout_batch_size 64 \
    --max_samples 1000000 \
    --max_epochs 1 \
    --prompt_max_len 1024 \
    --generate_max_len 1024 \
    --zero_stage 3 \
    --bf16 \
    --actor_learning_rate 5e-7 \
    --critic_learning_rate 9e-6 \
    --init_kl_coef 0.1 \
    --prompt_data ${working_dir}${data_info} \
    --input_key input \
    --label_key label \
    --apply_chat_template \
    --normalize_reward \
    --flash_attn \
    --adam_offload \
    --vllm_sync_backend nccl \
    --save_steps 1500 \
    --save_hf_ckpt \
    --ckpt_path ${pretrain_model_dir}/ckpt/ \
    --gradient_checkpointing"